### ISSUE TITLE
malan holds a large connection pool

### ISSUE THREAD

**Issue by cainlevy** [FreedomBen/malan#32]
It appears that Malan holds a large connection pool. Is it possible to dynamically allocate connections as needed, to more gracefully coexist on a smaller Postgres database with a lower `max_connections`/`shared_buffers`?

**Comment by FreedomBen** [comment]
I haven't been able to find a way to dynamically allocate as needed, but there is an env var that makes it trivial to change the number held per instance.  It requires a rolling restart of the deployment to change, but is pretty easy.

will continue to keep eyes open though as dynamic would be really nice.
